const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
function setup(){const ctx=vm.createContext({window:{}});vm.runInContext(fs.readFileSync(path.join(__dirname,'../js/data.js'),'utf8').replace('window.AO = {};','var AO = {};'),ctx);vm.runInContext(fs.readFileSync(path.join(__dirname,'../js/engine.js'),'utf8'),ctx);return {A:ctx.AO,g:new ctx.AO.Game()};}
function place(e,x,y){Object.assign(e,{x,y,px:x*32,py:y*32,fromX:x*32,fromY:y*32,step:1});}
function advance(g,seconds){for(let i=0;i<seconds*60;i++)g.update(1/60,new Set());}
test('map dimensions and all spawn/loot positions are valid',()=>{const {A,g}=setup();assert.equal(A.MAP.length,A.HEIGHT);for(const row of A.MAP)assert.equal(row.length,A.WIDTH);for(const e of [g.player,...g.enemies,...g.loot])assert.ok(g.walkable(e.x,e.y));});
test('walls, pillars, tombs and boundaries strictly block movement',()=>{const {g}=setup();g.enemies=[];for(const [x,y,dx,dy]of [[1,1,-1,0],[9,6,1,0],[4,7,1,0],[1,1,0,-1]]){place(g.player,x,y);assert.equal(g.move(g.player,dx,dy),false);assert.equal(g.player.x,x);assert.equal(g.player.y,y);}assert.equal(g.walkable(-1,5),false);assert.equal(g.walkable(26,5),false);});
test('movement interpolates and reserves origin and destination',()=>{const {g}=setup();assert.equal(g.move(g.player,1,0),true);assert.equal(g.player.x,9);assert.equal(g.player.px,256);assert.equal(g.occupied(8,10,g.enemies[0]),true);assert.equal(g.occupied(9,10,g.enemies[0]),true);assert.equal(g.move(g.player,1,0),false);advance(g,.2);assert.equal(g.player.px,288);assert.equal(g.player.step,1);assert.equal(g.occupied(8,10,g.enemies[0]),false);});
test('target, range and line of sight rejected without spending mana',()=>{const {g}=setup();const mana=g.player.mana;assert.equal(g.cast(0),false);g.select(5);assert.equal(g.cast(0),false);place(g.player,5,2);g.select(0);place(g.target,7,2);assert.equal(g.cast(0),false);assert.equal(g.player.mana,mana);assert.equal(g.cooldowns[0],0);});
test('instant damage, mana cost and cooldown are enforced',()=>{const {g}=setup();g.select(0);assert.equal(g.cast(0),true);assert.equal(g.enemies[0].hp,145);assert.equal(g.player.mana,220);assert.equal(g.cast(0),false);assert.equal(g.enemies[0].hp,145);});
test('insufficient mana rejects cast without damage or cooldown',()=>{const {g}=setup();g.select(0);g.player.mana=0;assert.equal(g.cast(2),false);assert.equal(g.enemies[0].hp,210);assert.equal(g.cooldowns[2],0);});
test('paralysis stops movement; cleanse and potions work while paralyzed',()=>{const {g}=setup();g.player.paralyzed=2;assert.equal(g.move(g.player,1,0),false);g.player.hp=100;assert.equal(g.cast(5),true);assert.equal(g.player.hp,200);assert.equal(g.cast(4),true);assert.equal(g.player.paralyzed,0);assert.equal(g.move(g.player,1,0),true);});
test('enemy paralysis prevents AI movement and attacks',()=>{const {g}=setup();g.select(0);place(g.target,9,10);assert.equal(g.cast(1),true);const hp=g.player.hp;advance(g,1);assert.equal(g.player.hp,hp);assert.ok(g.target.paralyzed>2);assert.equal(g.target.x,9);});
test('potions cap resources and consume exactly one item',()=>{const {g}=setup();g.player.mana=220;const stack=g.inventory.find(s=>s.kind==='mana');assert.equal(g.cast(6),true);assert.equal(g.player.mana,240);assert.equal(stack.count,23);assert.equal(g.cast(6),false);assert.equal(stack.count,23);});
test('casting and drinking during a step do not stop movement',()=>{const {g}=setup();g.select(0);g.move(g.player,1,0);assert.equal(g.cast(0),true);assert.equal(g.cast(6),true);advance(g,.2);assert.equal(g.player.x,9);assert.equal(g.player.px,288);});
test('melee costs energy and does not damage beyond reach',()=>{const {g}=setup();g.select(0);assert.equal(g.cast(7),false);place(g.target,9,10);assert.equal(g.cast(7),true);assert.equal(g.player.energy,92);assert.equal(g.target.hp,182);});
test('death creates loot; collection stacks and removes floor items',()=>{const {g}=setup();g.select(0);const e=g.target;g.damage(e,500);assert.equal(e.hp,0);assert.equal(g.target,null);assert.equal(g.kills,1);const oldGold=g.gold,oldMana=g.inventory.find(i=>i.kind==='mana').count;place(g.player,e.x,e.y);g.pickup();assert.equal(g.gold,oldGold+35);assert.equal(g.inventory.find(i=>i.kind==='mana').count,oldMana+2);assert.equal(g.loot.filter(i=>i.x===e.x&&i.y===e.y).length,0);g.pickup();assert.equal(g.gold,oldGold+35);});
test('BFS routes an enemy around an obstacle',()=>{const {g}=setup();g.enemies=g.enemies.slice(0,1);const e=g.enemies[0];place(e,9,6);place(g.player,11,6);for(let i=0;i<12;i++){g.chase(e);e.step=1;e.px=e.x*32;e.py=e.y*32;assert.ok(g.walkable(e.x,e.y));}assert.equal(Math.abs(e.x-g.player.x)+Math.abs(e.y-g.player.y),1);});
test('pause freezes simulation and blocks actions',()=>{const {g}=setup();g.paused=true;const before=g.time;g.update(1,new Set(['w']));assert.equal(g.time,before);assert.equal(g.player.y,10);assert.equal(g.cast(0),false);});
test('defeat freezes simulation; reset restores initial state',()=>{const {g}=setup();g.player.hp=1;place(g.enemies[0],9,10);g.enemies[0].attack=0;advance(g,.1);assert.equal(g.dead,true);assert.equal(g.player.hp,0);assert.equal(g.cast(5),false);g.reset();assert.equal(g.dead,false);assert.equal(g.player.hp,360);assert.equal(g.kills,0);assert.equal(g.enemies.length,7);});
test('quest reward occurs once and remaining loot can be collected',()=>{const {g}=setup();for(const e of g.enemies)g.damage(e,e.hp);assert.equal(g.won,true);assert.equal(g.kills,7);assert.equal(g.gold,590);assert.equal(g.dead,false);place(g.player,11,10);g.pickup();assert.equal(g.gold,635);});
